Repository LikeLion-13th-SKHU/LikeLion-13th-TEAM03-FE, pull requests merged in 2025-08, with the labels that each got.

#10 업종 추천 질문 페이지 제작
  sambakja/src/components/IndustryRecommendationQuestion.css
  sambakja/src/components/IndustryRecommendationQuestion.jsx
Labels: feature, design

#22 해당하는 행정동으로 지도가 이동하는 기능 구현 및 패널 디자인 수정
  sambakja/src/components/KakaoMap.css
  sambakja/src/components/KakaoMap.jsx
  sambakja/src/data/guDongMap.js
  sambakja/src/data/guDongMapWithCoords.js
Labels: docs, feature, design

#28 지도 행정구에 따른 폴리곤 작업 및 패널 디자인 변경
  sambakja/index.html
  sambakja/public/seoul_gu_polygons.json
  sambakja/src/components/KakaoMap.css
  sambakja/src/components/KakaoMap.jsx
  sambakja/src/data/guList.js
  sambakja/vite.config.js
Labels: feature, design

#40 지도 행정동 마커
  sambakja/src/components/KakaoMap.css
  sambakja/src/components/KakaoMap.jsx
  sambakja/src/data/guDongMapWithCoords.js
Labels: feature, chore, design

#41 [design](#39) 업종 추천 리포트 페이지 디자인 수정
  sambakja/src/components/IndustryRecommendationReport.jsx
Labels: design

#42 [design] 디자인 수정
  sambakja/src/App.jsx
  sambakja/src/GlobalStyle.js
  sambakja/src/components/BizFeature.jsx
  sambakja/src/components/CommercialAnalysisReport.css
  sambakja/src/components/CommercialAnalysisReport.jsx
  sambakja/src/components/Footer.jsx
  sambakja/src/components/GuideList.jsx
  sambakja/src/components/HighlightText.jsx
  sambakja/src/components/HomeHeader.jsx
  sambakja/src/components/Industry.jsx
  sambakja/src/components/IndustryRecommendationQuestion.jsx
  sambakja/src/components/IndustryRecommendationReport.css
  sambakja/src/components/IndustryRecommendationReport.jsx
  sambakja/src/components/Inquiry.jsx
  sambakja/src/components/KakaoMap.jsx
  sambakja/src/components/LocationalCharacteristics.jsx
  sambakja/src/components/Population.jsx
  sambakja/src/components/RecommendationCard.jsx
  sambakja/src/pages/AboutPage.jsx
  sambakja/src/pages/CommercialAnalysisReportPage.jsx
  sambakja/src/pages/HomePage.jsx
  sambakja/src/pages/IndustryRecommendationReportPage.jsx
  sambakja/src/pages/PolicyGuidePage.jsx
  sambakja/src/pages/PolicyPage.jsx
  sambakja/src/style/CommercialAnalysisReport.css
  sambakja/src/style/IndustryRecommendationQuestion.css
  sambakja/src/style/IndustryRecommendationReport.css
  sambakja/src/style/Inquiry.css
Labels: feature, chore, design
